# Generated by Django 5.0.4 on 2024-04-05 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('abstract', models.TextField()),
                ('publication_date', models.DateField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('group_description', models.TextField()),
                ('rec_list_updated', models.BooleanField(default=True)),
                ('papers', models.ManyToManyField(to='papers.paper')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendPapersList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.grouppaper')),
                ('papers', models.ManyToManyField(to='papers.paper')),
            ],
        ),
    ]
